package exception.finallyTest;

public class Test {
public static void main(String args[]){
	A a = new A();
	int i=a.getValue();
	System.out.println(i);
}
}
